version: '3.9'

services:

  db:
    image: postgres:15
    container_name: postgres_secure
    restart: unless-stopped
    user: postgres
    env_file: .env
    environment:
      POSTGRES_INITDB_ARGS: "--auth-local=scram-sha-256"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/backup:/backup
    networks:
      - backend_net
    ports:
      - "127.0.0.1:5432:5432"

  api:
    build: ./api
    container_name: api_service
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./api:/app
    networks:
      - backend_net
    ports:
      - "8000:8000"

  streamlit:
    image: python:3.11-slim
    container_name: streamlit_ui
    working_dir: /app
    volumes:
      - ./streamlit:/app
      - ./api:/app/api
    env_file:
      - .env
    command: bash -c "pip install -r requirements.txt && streamlit run streamlit_app.py --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - db
    networks:
      - backend_net


networks:
  backend_net:

volumes:
  db_data:
